# Generated by Django 3.0.3 on 2020-02-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmenu',
            name='chat_enable',
            field=models.NullBooleanField(verbose_name='同步到微信'),
        ),
    ]
